config/routes.rb
Rails.application.routes.draw do
  
  root 'application#home'

  get '/signin', to: 'sessions#sign_in'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('application#home')
  
 
  resources :users do 
      resources :tasks, only: [:index]          
  end 

  resources :projects  do 
    member do          
      get :completed
    end   
  end 

  resources :projects  do 
      member do          
        get :alltasks
      end  
     
  end 

  resources :projects  do 
      resources :tasks, only: [:create, :edit, :update, :destroy]  do 
        member do          
          patch :complete
        end         
      end
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :content, presence: true
  validates :content, uniqueness: { scope: :project_id,
                                  message: "Projects should have unique tasks" }
    belongs_to :project
    belongs_to :user

    scope :pending, -> { where(completed_at: '') }
    scope :recent, -> { order('tasks.updated_at DESC') }

    scope :completed, -> { where.not(completed_at: '') }

   def completed?
      !completed_at.blank?
   end 

   def project_name(id)    
    return Project.select(:id, :name, :status).where(id: id)
   end 

   def user_name(id)    
    return User.select(:id, :first_name, :last_name).where(id: id)
   end 
  
  end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user, only: [:create, :index, :destroy, :complete, :edit, :update]
  before_action :set_project, except: [:index]
  before_action :set_task, only: [:destroy, :complete, :edit, :update]

  def create  
    @task = @project.tasks.new(task_params)
    @task.user_id = current_user.id
    
    if @task.save
      flash[:notice] = "Successfully created task."
      respond_to do |format|
        format.json { render json: @project, status: 201}
      end
    else 
      flash[:notice] = "Ooopss ...Task was not created.Check if this task already exists or content can not be blank"
      respond_to do |format|
        format.json { render json: @project, status: 403}
      end
    end
  end

  def index    
    @user = User.find_by(id: params[:user_id])    
    respond_to do |format|
      format.json { render json: @user, status: 201}
    end
  end 

  def destroy  
    if @task.delete 
      flash[:notice] = "Task was deleted successfully !"
    else 
      flash[:notice] = "Task was not deleted !"
    end 
    redirect_to @project    
  end

  def complete     
    if @task.update_attribute(:completed_at, Time.now)      
      flash[:notice] = "Congrats ! Task was completed successfully !"
    else
      flash[:notice] = "Ooopps there was some error !"
    end 
    redirect_to @project
  end 

  def edit 
  end 

  def update 
    if @task.update(task_params)
      flash[:notice] = "Successfully updated task."
      redirect_to @project
    else 
      flash[:notice] = "Un-Successfully updated task."
      render :edit
    end
  end 
 
  private
  
  def set_task 
    @task = @project.tasks.find_by(id: params[:id])
  end 

  def set_project
    @project = Project.find_by(id: params[:project_id])
  end 

  def task_params
    params.require(:task).permit(:content, :project_id => @project.id)
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for ([@project, @project.tasks.build]) do |f| %>
    <%= f.label :content %>
    <%= f.text_field :content, placeholder: "New Task" %>
    <%= f.submit class: "btn btn-primary", data: { disable_with: false }%>
<% end %>

app/views/tasks/_task.html.erb
<% if @project.tasks.size == 0 
    flash[:notice] = "You have no tasks assigned...."
    end 
    @project.tasks.each do |t| %>  
          
    <div class="index_row clearfix">
        Task Assigned To:<%= t.user.first_name %>
                <% if @project.status=="active" && current_user == t.user  %>                   
                    <% if t.completed?  %>
                        <div class="complete">
                            <i style="opacity:0.4;" class="fa fa-check"></i> 
                        </div>
                        <div class="task">                              
                            <strike><%= t.content %></strike> 
                        </div>
                        <div class="trash">
                            <%= link_to  project_task_path(@project, t.id) , method:"delete",  data: { confirm: "Are you sure, you want to delete this task?" } do %>
                                <i class="fa fa-trash"></i> 
                            <% end %> 
                        </div>       
                    <% else %>
                            <div class="complete">
                                <%= link_to complete_project_task_path(@project, t.id) , method:"patch" do %>
                                    <i class="fa fa-check"></i>                       
                                <% end %>  
                            </div>
                            
                            <div class="task">
                            <%= link_to t.content, edit_project_task_path(@project.id, t.id)%>
                            </div>

                            <div class="trash">
                                <%= link_to  project_task_path(@project, t.id) , method:"delete",  data: { confirm: "Are you sure, you want to delete this task?" } do %>
                                    <i class="fa fa-trash"></i> 
                                <% end %> 
                            </div>   
                            
                    <% end %>
                <% else %>
                    <% if !t.completed?  %>
                        <div class="task">
                            <%= t.content %> 
                        </div>
                    <% else %> 
                            <div class="task">
                                <i style="opacity:0.4;" class="fa fa-check"></i>   
                                <strike><%= t.content%></strike>
                            </div>
                    <% end %>     
                <% end %>             

                                           
            </div>

            
           
    <% end %>
  
    


 

app/views/tasks/completed.html.erb
List of completed tasks for <%=@project.name %>
<br/>
<% if @tasks.size == 0%>
    <p>There are no tasks completed.</p>
<% end %>
<ul>
<% @tasks.each do |t| %>
    <li><%= t.content %></li>
<% end %>
</ul>

app/views/tasks/edit.html.erb
<h2 class="todo_list_title">
    <%= @project.name %>
</h2>
<div class="forms">
    <%= form_for ([@project, @task]) do |f| %>

        <%= f.label :content %>
        <%= f.text_field :content %>

        <%= f.submit class: "btn btn-primary" %>
    <% end %>
</div>

<div class="links">
    <%= link_to "Cancel", projects_path%>
</div>

app/views/tasks/index.html.erb
<% if @user && @user.tasks.pending.size == 0  %>
    You have completed all tasks. No Tasks are pending
<% else %>
    <% c1 = @user.tasks.collect { |p| p.project } %>
    <% c1.uniq.each do |project| %>
        
        <% if project.status == "active" %>
        
            <h4 class="todo_list_title">
                <%= link_to project.name, project_path(project) %>
            </h4>
            You have some pending tasks to take care of.........
                <% project.tasks.recent.each do |t|%>
                    <%if current_user == t.user %>

                        <div class="index_row clearfix">   
                        <% if !t.completed?  %> 
                                <%= t.content %>                           
                                <%= link_to "Edit Task", edit_project_task_path(project.id, t.id) %>                             
                        <% else %> 
                            <strike><%= t.content%></strike> 
                        <% end %> 
                        </div>
                    <% end %>
                <% end %>
        <% end %>
    <% end %>          
<% end %>

app/views/tasks/show.html.erb
<% t = @project.tasks.recent.first %>  
          
    <div class="index_row clearfix">
        Task Assigned To:<%= t.user.first_name %>
                <% if @project.status=="active" && current_user == t.user  %>                   
                    <% if t.completed?  %>
                        <div class="complete">
                            <i style="opacity:0.4;" class="fa fa-check"></i> 
                        </div>
                        <div class="task">                              
                            <strike><%= t.content %></strike> 
                        </div>
                        <div class="trash">
                            <%= link_to  project_task_path(@project, t.id) , method:"delete",  data: { confirm: "Are you sure, you want to delete this task?" } do %>
                                <i class="fa fa-trash"></i> 
                            <% end %> 
                        </div>       
                    <% else %>
                            <div class="complete">
                                <%= link_to complete_project_task_path(@project, t.id) , method:"patch" do %>
                                    <i class="fa fa-check"></i>                       
                                <% end %>  
                            </div>
                            
                            <div class="task">
                            <%= link_to t.content, edit_project_task_path(@project.id, t.id)%>
                            </div>

                            <div class="trash">
                                <%= link_to  project_task_path(@project, t.id) , method:"delete",  data: { confirm: "Are you sure, you want to delete this task?" } do %>
                                    <i class="fa fa-trash"></i> 
                                <% end %> 
                            </div>   
                            
                    <% end %>
                <% else %>
                    <% if !t.completed?  %>
                        <div class="task">
                            <%= t.content %> 
                        </div>
                    <% else %> 
                            <div class="task">
                                <i style="opacity:0.4;" class="fa fa-check"></i>   
                                <strike><%= t.content%></strike>
                            </div>
                    <% end %>     
                <% end %>             

                                           
            </div>

            
           