config/routes.rb
Rails.application.routes.draw do
  
  root 'application#home'

  get '/signin', to: 'sessions#sign_in'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('application#home')
  
 
  resources :users do 
      resources :tasks, only: [:index]          
  end 

  resources :projects  do 
    member do          
      get :completed
    end   
  end 

  resources :projects  do 
      member do          
        get :alltasks
      end  
     
  end 

  resources :projects  do 
      resources :tasks, only: [:create, :edit, :update, :destroy]  do 
        member do          
          patch :complete
        end         
      end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
    validates :name, presence: true, uniqueness: true

    has_many :tasks
    has_many :users, through: :tasks

    scope :status, -> { where(status: 'active') }
    scope :recent, -> { order('projects.updated_at DESC') }

  end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController  
  before_action :authenticate_user
  before_action :set_project, only: [:show, :edit, :update, :destroy, :completed, :alltasks]

  def index    
    if current_user.admin
      @users = User.where(admin: false)  
      @projects = Project.all.recent    
    else 
      @users = User.where(id: current_user.id)
      @projects = Project.all.status
    end
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @projects, status: 201}
    end  
  end

  def show  
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @project, status: 201}
    end  
  end

  def new
    @project = Project.new
    @task = Task.new
  end

  def create 
    @project = Project.new(project_params)
    if @project.save
      flash[:notice] = "Successfully created Project."
      redirect_to @project
    else 
      flash[:notice] = "Un-Successfully created Project."
      render :new
    end
  end

  def edit
  end

  def update     
    if @project.update(project_params)
      flash[:notice] = "Successfully updated project."
      redirect_to @project
    else 
      flash[:notice] = "Un-Successfully updated project."
      render :edit
    end
  end

  def destroy     
    if @project.delete
         @tasks = Task.where(:project_id => @project.id)
         
         if @tasks.delete_all
          flash[:notice] = "Successfully deleted this Project !! All tasks for this Project were also deleted !!"
          redirect_to @project
         end
     else
         flash[:notice] = "This Project was not deleted !!"         
         redirect_to projects_path
     end
  end 

  def completed
    respond_to do |format|
      format.json { render json: @project, status: 201}
    end
  end 

  def alltasks  
    respond_to do |format|
      format.json { render json: @project, status: 201}
    end
  end 

  private
  def set_project
    @project = Project.find_by(id: params[:id])
  end 

  def project_params
    params.require(:project).permit(:name, :description, :status)
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
    
    <%= f.label :name %>
    <%= f.text_field :name %>
      
    <br>
    <%= f.label :description %>
    <%= f.text_field :description %>

    <br>
    <%= f.label :status %>
    <%= f.radio_button :status, "active", checked: true %>
    <%= f.label :status_active, "Active" %>

    <%= f.radio_button :status, "deactive" %>
    <%= f.label :status_inactive, "Deactive" %>

    <br>
    <br>
<%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/projects/edit.html.erb
<div class="forms">
    <%= render 'form' %>
</div>

<div class="links">
    <%= link_to "Cancel", projects_path%>
</div>

app/views/projects/index.html.erb
<h1 class="todo_list_title">List Of Projects</h1>
<% if flash[:notice] %>
<div id="notice"><%= flash[:notice] %></div>
<% end %>
<% if @projects.size == 0
    flash[:notice] = "You have no acitve projects assigned...."
  end 
%>
<% @projects.each do |project| %>
  
  <div class="index_row clearfix">

    <% if project.status == "active" %>
      <h2 class="todo_list_title">
        <%= link_to project.name, project_path(project) %>  
      </h2>
      
      <h2 class="todo_list_sub_title">      
        <%= truncate(project.description) %>  
      </h2>
      
      <br/> 

      <% if current_user.admin %>
      <div class="links">
        
        <%= link_to "Edit Project", [:edit, project] %>
        <%=   link_to project_path(project), method: :delete, data: { confirm: 'Are you sure you want to delete this Project? All project tasks shall also be deleted.' } do %> 
          
          <i class="fa fa-trash"></i>   
        <% end %>   
      </div>
      <% else %>
        <div class="links">
          <%= link_to "Show Tasks", project_path(project) %>
        </div>
      <% end %>     

    <% else %>
        <h2 class="todo_list_title">
          <strike><%= link_to project.name, project_path(project) %>  </strike>
        </h2>
              
        <h2 class="todo_list_sub_title">
          <strike><%= project.description %>  </strike>
        </h2>
        <div class="links">
          <%= link_to "Edit Project", [:edit, project] %>
          <%=   link_to project_path(project), method: :delete, data: { confirm: 'Are you sure you want to delete this Project? All project tasks shall also be deleted.' } do %> 
          
            <i class="fa fa-trash"></i>   
          <% end %>
        </div>
      
  <% end %>

  
  </div>
  
<% end %>

<div class="links">
  <% if current_user.admin %>  
      <p><%= link_to 'New Projects', new_project_path %></p>  
  <% end %>
</div>

app/views/projects/new.html.erb
<div class="forms">
    <%= render 'form' %>
</div>

<div class="links">
    <%= link_to "Cancel", projects_path%>
</div>

app/views/projects/show.html.erb
<% if flash[:notice] %>
<div id="notice"><%= flash[:notice] %></div>
<% end %>



<p>
    <h1 class="todo_list_title">
        <%= @project.name %>
    </h1>    
    <h2 class="todo_list_sub_title">  
        <%= @project.description %>
    </h2>
</p>



<div class="links">
    <%= link_to "Show Completed Tasks", completed_project_path(@project), class: "project_completed_tasks"%>
    <%= link_to "Show All Tasks", alltasks_project_path(@project), class: "project_all_tasks" %>
</div>

<div id="todo_items_wrapper">  
<div class="projecttasks">
</div>    
    <% if @project.status == "active" %>
    Create Task:
        <div class="forms">
            <%= render "tasks/form" %>
        </div>
    <% end %>
</div>


<div class="links">
    <% if current_user.admin %>            
        <%= link_to "Edit Project", edit_project_path(@project) %> ||
    <% end %>
     <%= link_to "Back", projects_path%>
</div>