config/routes.rb
Rails.application.routes.draw do
  
  root 'application#home'

  get '/signin', to: 'sessions#sign_in'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('application#home')
  
 
  resources :users do 
      resources :tasks, only: [:index]          
  end 

  resources :projects  do 
    member do          
      get :completed
    end   
  end 

  resources :projects  do 
      member do          
        get :alltasks
      end  
     
  end 

  resources :projects  do 
      resources :tasks, only: [:create, :edit, :update, :destroy]  do 
        member do          
          patch :complete
        end         
      end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManagement</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  </head>

  <body>
  <a href="<%= root_url %>"/>Home</a>
    
              <% if current_user %>
                <li><%= link_to "Hello, #{current_user.first_name}!", user_path(current_user) %></li>
                <li><%= link_to "Projects Dashboard", projects_path %></li>
                <li><%= link_to "Log Out", signout_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "Sign Up", new_user_path %></li>
                <li><%= link_to "Sign In", signin_path %></li>
                OR 
               
                <li><%= link_to "Sign in with Github" ,  "/auth/github"  %>    
                </li>
              <% end %>


     
      <div class="container">
        <%= yield %>
      </div>
  </body>
</html>

app/views/layouts/home_page.html.erb
<h2 class="todo_list_title">
Project Management Rails App
</h2>
<h2 class="todo_list_sub_title"> 
Where Small and medium size companies can manage their projects with ease !
</h2>

<h2 class="todo_list_sub_title"> 
<img src="https://www.g2msolutions.com.au/hs-fs/hubfs/Top_8_tips_to_effective_client_management1.jpg?t=1537666088710&width=900&name=Top_8_tips_to_effective_client_management1.jpg" alt="project management link" style="width:800px;height:400px;"/>
</h2>